### ISSUE TITLE
Chances

### ISSUE THREAD

**Issue by animalillo** [iDroid-Project/openiBoot#32]
I have an ipod touch 4 taking dust in my house and was thinking on giving some use to it, but ios is useless to me.

I wont like brick it, so I was wondering if the documentation on this project is still good and what should I do / avoid doing to keep my device working. I also want to know if the process can be undone and get the apple shitty os back to the ipod.

**Comment by nickpack** [comment]
The iPod 4G port was never completed, so there is no port.

**Comment by animalillo** [comment]
I assume by this answer that there is never going to be ipod 4G support

**Comment by nickpack** [comment]
The project has been abandoned for years now, I am not aware of anyone working on any of it.
