### ISSUE TITLE
gelf.h

### ISSUE THREAD

**Issue by TheonlyGermanGuy** [iDroid-Project/openiBoot#33]
Goodday.

I have been trying to build openiBoot on Mac OSX with the official toolchain, though there's a problem when compiling the mk8900image program. The error is printed here:

```
$ scons iPhone4 
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
gcc -o mk8900image/mk8900image.o -c mk8900image/mk8900image.c
mk8900image/mk8900image.c:7:10: fatal error: 'gelf.h' file not found
#include <gelf.h>
         ^
1 error generated.
scons: *** [mk8900image/mk8900image.o] Error 1
scons: building terminated because of errors.
```

I have tried installing libelf from macports, but after setting the CPATH to /opt/include/, still nothing changed.

**Comment by nickpack** [comment]
@TheonlyGermanGuy I'll have to look into this, but it just looks like an issue with paths.

**Comment by TheonlyGermanGuy** [comment]
Ok, I will try to check it again, maybe there was a logical error on my side.

**Comment by TheonlyGermanGuy** [comment]
Changing the Paths doesn't seem to help, does the script set it's own Path?

**Comment by TheonlyGermanGuy** [comment]
Installing libe
