### ISSUE TITLE
What Apple devices are supported?

### ISSUE THREAD

**Issue by thanone2** [iDroid-Project/openiBoot#48]

**Comment by mirh** [comment]
All the devices vulnerable to limera1n presumably, and they are kinda mentioned in the readme

**Comment by nickpack** [comment]
Build targets are all listed: https://github.com/iDroid-Project/openiBoot?tab=readme-ov-file#compiling

From what I understand now though, getting the compiler toolchain to work in modern OS is a bit of a mission - nobody has touched any of this in a long time.

**Comment by thanone2** [comment]
thanks man
